import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./_global-css/normalize.css";
import "./_global-css/bootstrap-mock.css";
import "./_global-css/global.css";
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reellance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={rubik.className}>
        <link rel="icon" href="/favicon.png" sizes="any" />
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
