import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
import "./global-css/normalize.css";
import "./global-css/bootstrap-mock.css";
import "./global-css/global.css";
import Header from "./components/Header/header";
import Footer from "./components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reellance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={inter.className}>
        <link rel="icon" href="/favicon.png" sizes="any" />
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
